/*******************************************************************************
**  FILE-NAME: Sd_Cfg.c                                                     **
**                                                                            **
**  MODULE-NAME: Sd                                                           **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.1.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../TestAppl/App_Sd_All/PC_Config/xml/App_Sd_All.arxml
 *   ../../../171_Sd_DELIVERY/ssc/generator/KPIT_AUTOSAR_R24-11_SD_BSWMD.arxml
 *   ../../../171_Sd_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Wed 2025 Jul 02 19:00:22 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
         /*******************************************************************************
         **                   MISRA-C:2012 violations Section                          **
         *******************************************************************************/
         /**
         * #page misra_violations MISRA-C:2012 violations
         *
         * #section Sd_Cfg_C_REF_1
         * Violates MISRA 2012 Advisory Rule 20.1, #include directives should only be
         * preceded by preprocessor directives or comments
         *
         * #section Sd_Cfg_C_REF_2
         * Violates MISRA 2012 Required Dir-1.1, [L] Number of macro definitions exceeds
         * 4095 - program does not conform strictly to ISO:C99.
         **/
         /*#violates #ref Sd_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 20.1*/
         /*PRQA S 5087 EOF */
         /* violates #ref Sd_Cfg_C_REF_2 Violates MISRA 2012 Dir-1.1 */
         /* PRQA S 0380 EOF */
         
         /** #section Sd_Cfg_C_REF_1
             * Violates MISRA 2012 Advisory Rule 20.1,
             * #include directives should only be preceded by preprocessor directives or
             * comments.
             *
             **/
             
            /**
              *
              * #section Sd_Cfg_C_REF_1
              * Violates MISRA 2012 Advisory Rule 1.1,
              * Number of Macro definitions exceed 1024.
              *
              **/
              
            /* Violates #ref Sd_Cgf_C_REF_1 Violates MISRA 2012 Required Rule 20.1 */
            /* PRQA S 5087 EOF */
                #include "Sd_Cfg.h"
            /* Violates #ref Sd_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 1.1 */
            /* PRQA S 0857 EOF */
        /* Violates #ref Sd_Cfg_C_REF_2 Violates INT02 Msg(qac-10.1.0-1290) */
            /*PRQA S 1290 EOF*/
		/* Violates #ref Sd_Cfg_C_REF_2 Violates INT02 DCL06,EXP07 Msg(qac-10.1.0-3132) */
		/*PRQA S 3132 EOF*/
		/* #Violates #ref SD_Cfg_C_REF_2 PRE08 Msg(certccm-2.1.0-5002)  */
            /*PRQA S 5002 EOF*/
		/* #Violates #ref SD_Cfg_REF_2 CMN-0:CMN-0.1,CMN-0.1 Msg(qac-10.1.0-4810)  */
           
      /* #Violates #ref SD_Cfg_REF_2 CMN-0:CMN-0.1,CMN-0.1 Msg(qac-10.1.0-4810)  */
             /*PRQA S 4810 EOF */
/*#Violates #ref SD_Cfg_REF_2 CMN-0:CMN-0.1,CMN-0.1   M3CM-2:Rule-9.3 Msg(qac-10.1.0-0686)*/
         /*PRQA S 0686 EOF */
         
         
         /******************************************************************************/
             #include "Sd.h"
             #include "Sd_IntTypes.h"
             #include "Sd_Internal.h"
             #include "Sd_Version.h"
         

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (SD_VERSION_AR_RELEASE_MAJOR_VERSION != SD_AR_RELEASE_MAJOR_VERSION)
  #error "SD Code : Mismatch in Specification Major Version"
#endif

#if (SD_VERSION_AR_RELEASE_MINOR_VERSION != SD_AR_RELEASE_MINOR_VERSION)
  #error "SD Code : Mismatch in Specification Minor Version"
#endif

#if (SD_VERSION_AR_RELEASE_REVISION_VERSION != SD_AR_RELEASE_REVISION_VERSION)
  #error "SD Code : Mismatch in Specification Revision Version"
#endif

#if (SD_VERSION_SW_MAJOR_VERSION != SD_SW_MAJOR_VERSION)
  #error "SD Code : Mismatch in Software Major Version"
#endif

#if (SD_VERSION_SW_MINOR_VERSION != SD_SW_MINOR_VERSION)
  #error "SD Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/
   #define SD_START_SEC_VAR_CLEARED_BOOLEAN
   #include "Sd_MemMap.h"
   VAR(boolean, SD_VAR_CLEARED) Sd_GaaAclPolicyFlag  = SD_ZERO;
   #define SD_STOP_SEC_VAR_CLEARED_BOOLEAN
   #include "Sd_MemMap.h"
   
   #if (SD_RAM_BLOCK == STD_ON)
   #define SD_START_SEC_VAR_NO_INIT_UNSPECIFIED
   #include "Sd_MemMap.h"
   VAR(Sd_ProviderConsumerListType, SD_VAR_CLEARED)
    Sd_GaaClient_Server_List[SD_NO_OF_RAM_ALLOWED_SERVER_CLIENT_PROVIDER_CONSUMER];
   #define SD_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
   #include "Sd_MemMap.h"
   #endif
       
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaServerHandleMapArray */
   CONST(Sd_ServicesType, SD_CONST) Sd_GaaServerHandleMapArray[8] = {
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

       
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaClientHandleMapArray */
   CONST(Sd_ServicesType, SD_CONST) Sd_GaaClientHandleMapArray[4] = {
     0,
     1,
     2,
     3
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

       
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaConEvGrpHandleMapArray */
   CONST(Sd_ServicesType, SD_CONST) Sd_GaaConEvGrpHandleMapArray[4] = {
     0,
     1,
     2,
     3
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

       
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaRxPduMapArray */
   CONST(Sd_ServicesType, SD_CONST) Sd_GaaRxPduMapArray[4] = {
   1,
   0,
   0,
   1
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

       
   
   #define SD_START_SEC_CONFIG_DATA_8
   #include "Sd_MemMap.h"
   
   /* Sd_GSaaConfigurationOption */
   static CONST(uint8, SD_CONST) Sd_GSaaConfigurationOption[124] = {
   	
   0/* Sd_GaaServerServiceStatic :
              1 - SdConfig_0 SdInstance_0 SdServerService_0 */,
   0,
   24,
   0,
   0,
   12,
   (uint8)'P',
   (uint8)'l',
   (uint8)'u',
   (uint8)'g',
   (uint8)'i',
   (uint8)'n',
   (uint8)'s',
   (uint8)'=',
   (uint8)'J',
   (uint8)'P',
   (uint8)'E',
   (uint8)'G',
   8,
   (uint8)'P',
   (uint8)'l',
   (uint8)'u',
   (uint8)'g',
   (uint8)'i',
   (uint8)'n',
   (uint8)'s',
   (uint8)'=',
   0,
   0/* Sd_GaaClientServiceStatic :
            2 - SdConfig_0 SdInstance_0 SdClientService_0 */,
   0,
   16,
   0,
   0,
   6,
   (uint8)'a',
   (uint8)'b',
   (uint8)'c',
   (uint8)'=',
   (uint8)'b',
   (uint8)'1',
   6,
   (uint8)'a',
   (uint8)'b',
   (uint8)'c',
   (uint8)'=',
   (uint8)'d',
   (uint8)'2',
   0,
   0/* Sd_GaaClientServiceStatic :
            3 - SdConfig_0 SdInstance_0 SdClientService_1 */,
   0,
   14,
   0,
   0,
   6,
   (uint8)'a',
   (uint8)'b',
   (uint8)'c',
   (uint8)'=',
   (uint8)'d',
   (uint8)'1',
   4,
   (uint8)'a',
   (uint8)'b',
   (uint8)'c',
   (uint8)'=',
   0,
   0/* Sd_GaaClientServiceStatic :
            4 - SdConfig_0 SdInstance_0 SdClientService_2 */,
   0,
   16,
   0,
   0,
   6,
   (uint8)'a',
   (uint8)'b',
   (uint8)'c',
   (uint8)'=',
   (uint8)'d',
   (uint8)'1',
   6,
   (uint8)'a',
   (uint8)'b',
   (uint8)'c',
   (uint8)'=',
   (uint8)'d',
   (uint8)'2',
   0,
   0/* Sd_GaaClientServiceStatic :
            5 - SdConfig_0 SdInstance_0 SdClientService_3 */,
   0,
   16,
   0,
   0,
   6,
   (uint8)'a',
   (uint8)'b',
   (uint8)'c',
   (uint8)'=',
   (uint8)'d',
   (uint8)'1',
   6,
   (uint8)'a',
   (uint8)'b',
   (uint8)'c',
   (uint8)'=',
   (uint8)'d',
   (uint8)'2',
   0,
   0/* InstanceHostname :
                 6 - SdConfig_0 SdInstance_0 */,
   0,
   14,
   0,
   0,
   11,
   (uint8)'h',
   (uint8)'o',
   (uint8)'s',
   (uint8)'t',
   (uint8)'n',
   (uint8)'a',
   (uint8)'m',
   (uint8)'e',
   (uint8)'=',
   (uint8)'s',
   (uint8)'d',
   0,
   };
   #define SD_STOP_SEC_CONFIG_DATA_8
   #include "Sd_MemMap.h"

        
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaSoConId */
   CONST(SoAd_SoConIdType, SD_CONST) Sd_GaaSoConId[15] = 
   {
     0,     2,     1,     3,     4,     5,     6,     7,     11,     13,     14,     15,     18,     19,     20
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

       
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaMulticastSoConGrpIndex */
   CONST(SoAd_SoConIdType, SD_CONST) Sd_GaaMulticastSoConGrpIndex[2] = {
   7,
   6
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

        
   #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
   #include "Sd_MemMap.h"
   static CONST(Sd_ServerTimerStaticType, SD_CONST) Sd_GSaaServerTimerStatic[2] =
   {
     /* Sd_GSaaServerTimerStatic_0 - SdInstance_0_SdServerTimer_0 */
     {
       
       /* ulServerTimerTtlsec */
       0x3U,
       
       /* ulInitialOfferDelayMax */
        0x5,
       
       /* ulInitialOfferDelayMin */
       0x5,
       
       /* ulInitialOfferRepetitionBaseDelay */
       0x0,
       
       /* ulTimerOfferCyclicDelay */
       0x0,
       
       /* ulRequestResponseMaxDelay */
       0x0,
       
       /* ulRequestResponseMinDelay */
        0x0,
       
       /*  ucInitialOfferRepetitionsMax  */
        0x0
     },
     /* Sd_GSaaServerTimerStatic_1 - SdInstance_1_SdServerTimer_0 */
     {
       
       /* ulServerTimerTtlsec */
       0x3U,
       
       /* ulInitialOfferDelayMax */
        0x5,
       
       /* ulInitialOfferDelayMin */
       0x5,
       
       /* ulInitialOfferRepetitionBaseDelay */
       0x0,
       
       /* ulTimerOfferCyclicDelay */
       0x0,
       
       /* ulRequestResponseMaxDelay */
       0x0,
       
       /* ulRequestResponseMinDelay */
        0x0,
       
       /*  ucInitialOfferRepetitionsMax  */
        0x0
     }
   };
    #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #include "Sd_MemMap.h" 

       
   #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
   #include "Sd_MemMap.h"
   CONST(Sd_ServerServiceStaticType, SD_CONST) Sd_GaaServerServiceStatic[8] =
   {
     /* Sd_GaaServerServiceStatic : 0 - SdInstance_0_SdServerService_0 */
     {
       
       /* ulMinorVersion */
       0x64U,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[1],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[2],
       
       /* pServerTimer */
       &Sd_GSaaServerTimerStatic[0],
       
       /* pConfigOption */
       &Sd_GSaaConfigurationOption[1],
       
       /*  usHandleId */
       0x0,
       
       /* usServiceId */
       0xAU,
       
       /* usInstanceId */
       0x8,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* usBaseEvHandlerIndex */
       0x0,
       
       /* usNoOfEvHandlers */
       0x2,
       
       /* usServerSelfIndex */
       0x0,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /*  ucMajorVersion */
       0x3,
       
       /* stServerStaticFlag */
       {
         
         /* blAutoAvaliable */
         0,
         
         /* blActivationRoGrpIdPresent */
         1,
         
         /* ucReserved  */
         0
       },
       
       /* usMaxNumOfIpAddressesInAcl */
       0,
       
       /* blAclEnable_Disable_Check */
       SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR
     },
     /* Sd_GaaServerServiceStatic : 1 - SdInstance_0_SdServerService_1 */
     {
       
       /* ulMinorVersion */
       0xFU,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[1],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[2],
       
       /* pServerTimer */
       &Sd_GSaaServerTimerStatic[0],
       
       /* pConfigOption */
       NULL_PTR,
       
       /*  usHandleId */
       0x1,
       
       /* usServiceId */
       0x5U,
       
       /* usInstanceId */
       0x0,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* usBaseEvHandlerIndex */
       0x2,
       
       /* usNoOfEvHandlers */
       0x1,
       
       /* usServerSelfIndex */
       0x1,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /*  ucMajorVersion */
       0xA,
       
       /* stServerStaticFlag */
       {
         
         /* blAutoAvaliable */
         0,
         
         /* blActivationRoGrpIdPresent */
         0,
         
         /* ucReserved  */
         0
       },
       
       /* usMaxNumOfIpAddressesInAcl */
       0,
       
       /* blAclEnable_Disable_Check */
       SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR
     },
     /* Sd_GaaServerServiceStatic : 2 - SdInstance_0_SdServerService_2 */
     {
       
       /* ulMinorVersion */
       0xFU,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[1],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[2],
       
       /* pServerTimer */
       &Sd_GSaaServerTimerStatic[0],
       
       /* pConfigOption */
       NULL_PTR,
       
       /*  usHandleId */
       0x2,
       
       /* usServiceId */
       0x5U,
       
       /* usInstanceId */
       0x1,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* usBaseEvHandlerIndex */
       0x0,
       
       /* usNoOfEvHandlers */
       0x0,
       
       /* usServerSelfIndex */
       0x2,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /*  ucMajorVersion */
       0xA,
       
       /* stServerStaticFlag */
       {
         
         /* blAutoAvaliable */
         0,
         
         /* blActivationRoGrpIdPresent */
         0,
         
         /* ucReserved  */
         0
       },
       
       /* usMaxNumOfIpAddressesInAcl */
       0,
       
       /* blAclEnable_Disable_Check */
       SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR
     },
     /* Sd_GaaServerServiceStatic : 3 - SdInstance_0_SdServerService_3 */
     {
       
       /* ulMinorVersion */
       0xFU,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[1],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[2],
       
       /* pServerTimer */
       &Sd_GSaaServerTimerStatic[0],
       
       /* pConfigOption */
       NULL_PTR,
       
       /*  usHandleId */
       0x3,
       
       /* usServiceId */
       0x5U,
       
       /* usInstanceId */
       0x0,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* usBaseEvHandlerIndex */
       0x0,
       
       /* usNoOfEvHandlers */
       0x0,
       
       /* usServerSelfIndex */
       0x3,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /*  ucMajorVersion */
       0x64,
       
       /* stServerStaticFlag */
       {
         
         /* blAutoAvaliable */
         0,
         
         /* blActivationRoGrpIdPresent */
         0,
         
         /* ucReserved  */
         0
       },
       
       /* usMaxNumOfIpAddressesInAcl */
       0,
       
       /* blAclEnable_Disable_Check */
       SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR
     },
     /* Sd_GaaServerServiceStatic : 4 - SdInstance_0_SdServerService_4 */
     {
       
       /* ulMinorVersion */
       0x1U,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[1],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[2],
       
       /* pServerTimer */
       &Sd_GSaaServerTimerStatic[0],
       
       /* pConfigOption */
       NULL_PTR,
       
       /*  usHandleId */
       0x4,
       
       /* usServiceId */
       0x5U,
       
       /* usInstanceId */
       0x2,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* usBaseEvHandlerIndex */
       0x3,
       
       /* usNoOfEvHandlers */
       0x1,
       
       /* usServerSelfIndex */
       0x4,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /*  ucMajorVersion */
       0x64,
       
       /* stServerStaticFlag */
       {
         
         /* blAutoAvaliable */
         0,
         
         /* blActivationRoGrpIdPresent */
         0,
         
         /* ucReserved  */
         0
       },
       
       /* usMaxNumOfIpAddressesInAcl */
       0,
       
       /* blAclEnable_Disable_Check */
       SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR
     },
     /* Sd_GaaServerServiceStatic : 5 - SdInstance_0_SdServerService_5 */
     {
       
       /* ulMinorVersion */
       0x2U,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[1],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[2],
       
       /* pServerTimer */
       &Sd_GSaaServerTimerStatic[0],
       
       /* pConfigOption */
       NULL_PTR,
       
       /*  usHandleId */
       0x5,
       
       /* usServiceId */
       0x5U,
       
       /* usInstanceId */
       0x2,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* usBaseEvHandlerIndex */
       0x4,
       
       /* usNoOfEvHandlers */
       0x1,
       
       /* usServerSelfIndex */
       0x5,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /*  ucMajorVersion */
       0x64,
       
       /* stServerStaticFlag */
       {
         
         /* blAutoAvaliable */
         0,
         
         /* blActivationRoGrpIdPresent */
         0,
         
         /* ucReserved  */
         0
       },
       
       /* usMaxNumOfIpAddressesInAcl */
       0,
       
       /* blAclEnable_Disable_Check */
       SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR
     },
     /* Sd_GaaServerServiceStatic : 6 - SdInstance_1_SdServerService_0 */
     {
       
       /* ulMinorVersion */
       0x2U,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[3],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[0],
       
       /* pServerTimer */
       &Sd_GSaaServerTimerStatic[0],
       
       /* pConfigOption */
       NULL_PTR,
       
       /*  usHandleId */
       0x6,
       
       /* usServiceId */
       0x2U,
       
       /* usInstanceId */
       0x2,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* usBaseEvHandlerIndex */
       0x0,
       
       /* usNoOfEvHandlers */
       0x0,
       
       /* usServerSelfIndex */
       0x6,
       
       /* ucSdInstanceIndex */
       0x1,
       
       /*  ucMajorVersion */
       0x2,
       
       /* stServerStaticFlag */
       {
         
         /* blAutoAvaliable */
         0,
         
         /* blActivationRoGrpIdPresent */
         0,
         
         /* ucReserved  */
         0
       },
       
       /* usMaxNumOfIpAddressesInAcl */
       0,
       
       /* blAclEnable_Disable_Check */
       SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR
     },
     /* Sd_GaaServerServiceStatic : 7 - SdInstance_1_SdServerService_1 */
     {
       
       /* ulMinorVersion */
       0x2U,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[3],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[0],
       
       /* pServerTimer */
       &Sd_GSaaServerTimerStatic[0],
       
       /* pConfigOption */
       NULL_PTR,
       
       /*  usHandleId */
       0x7,
       
       /* usServiceId */
       0x2U,
       
       /* usInstanceId */
       0x2,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* usBaseEvHandlerIndex */
       0x0,
       
       /* usNoOfEvHandlers */
       0x0,
       
       /* usServerSelfIndex */
       0x7,
       
       /* ucSdInstanceIndex */
       0x1,
       
       /*  ucMajorVersion */
       0x2,
       
       /* stServerStaticFlag */
       {
         
         /* blAutoAvaliable */
         0,
         
         /* blActivationRoGrpIdPresent */
         0,
         
         /* ucReserved  */
         0
       },
       
       /* usMaxNumOfIpAddressesInAcl */
       0,
       
       /* blAclEnable_Disable_Check */
       SD_FALSE,
       
       /* pServiceGroupRef */
       &Sd_GaaServicegroupStatic[0]
     }
   };
       
      #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
      #include "Sd_MemMap.h" 

       
    #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
    #include "Sd_MemMap.h"
    CONST(Sd_EvHandlerStaticType, SD_CONST) Sd_GaaEvHandlerStatic[5] =
    {
   /* Sd_GaaEvHandlerStatic : 
       	0 - SdInstance_0_SdServerService_0_SdEventHandler_0 */
   {
     
     /* pServerTimer */
     &Sd_GSaaServerTimerStatic[0],
     
     /* pConfigOption */
     NULL_PTR,
     
     /* usHandleId */
     0x0,
     
     /* usEventGroupId */
     0x9U,
     
     /* usMulticastThreshold */
     0x5,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddUdpTriggeringRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddTcpTriggeringRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddMulticastEventSoConId */
     0x0,
     
     /* usServerServiceIndex */
     0x0,
     
     /* usEvHandlerSelfIndex */
     0x0,
     
     /* stEvHandlerStaticFlag */
     {
       
       /* blUdpTriggeringRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       0,
       
       /* blTcpTriggeringRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blMulticastEventSoConPresent */
       0,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaEvHandlerStatic : 
       	1 - SdInstance_0_SdServerService_0_SdEventHandler_1 */
   {
     
     /* pServerTimer */
     &Sd_GSaaServerTimerStatic[0],
     
     /* pConfigOption */
     NULL_PTR,
     
     /* usHandleId */
     0x1,
     
     /* usEventGroupId */
     0xEU,
     
     /* usMulticastThreshold */
     0x5,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddUdpTriggeringRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddTcpTriggeringRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddMulticastEventSoConId */
     0x0,
     
     /* usServerServiceIndex */
     0x0,
     
     /* usEvHandlerSelfIndex */
     0x1,
     
     /* stEvHandlerStaticFlag */
     {
       
       /* blUdpTriggeringRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       0,
       
       /* blTcpTriggeringRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blMulticastEventSoConPresent */
       0,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaEvHandlerStatic : 
       	2 - SdInstance_0_SdServerService_1_SdEventHandler_0 */
   {
     
     /* pServerTimer */
     &Sd_GSaaServerTimerStatic[0],
     
     /* pConfigOption */
     NULL_PTR,
     
     /* usHandleId */
     0x2,
     
     /* usEventGroupId */
     0x19U,
     
     /* usMulticastThreshold */
     0x0,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddUdpTriggeringRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddTcpTriggeringRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddMulticastEventSoConId */
     0x0,
     
     /* usServerServiceIndex */
     0x1,
     
     /* usEvHandlerSelfIndex */
     0x2,
     
     /* stEvHandlerStaticFlag */
     {
       
       /* blUdpTriggeringRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       0,
       
       /* blTcpTriggeringRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blMulticastEventSoConPresent */
       0,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaEvHandlerStatic : 
       	3 - SdInstance_0_SdServerService_4_SdEventHandler_0 */
   {
     
     /* pServerTimer */
     &Sd_GSaaServerTimerStatic[0],
     
     /* pConfigOption */
     NULL_PTR,
     
     /* usHandleId */
     0x3,
     
     /* usEventGroupId */
     0x19U,
     
     /* usMulticastThreshold */
     0x0,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddUdpTriggeringRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddTcpTriggeringRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddMulticastEventSoConId */
     0x0,
     
     /* usServerServiceIndex */
     0x4,
     
     /* usEvHandlerSelfIndex */
     0x3,
     
     /* stEvHandlerStaticFlag */
     {
       
       /* blUdpTriggeringRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       0,
       
       /* blTcpTriggeringRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blMulticastEventSoConPresent */
       0,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaEvHandlerStatic : 
       	4 - SdInstance_0_SdServerService_5_SdEventHandler_0 */
   {
     
     /* pServerTimer */
     &Sd_GSaaServerTimerStatic[0],
     
     /* pConfigOption */
     NULL_PTR,
     
     /* usHandleId */
     0x4,
     
     /* usEventGroupId */
     0x1EU,
     
     /* usMulticastThreshold */
     0x0,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddUdpTriggeringRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddTcpTriggeringRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddMulticastEventSoConId */
     0x0,
     
     /* usServerServiceIndex */
     0x5,
     
     /* usEvHandlerSelfIndex */
     0x4,
     
     /* stEvHandlerStaticFlag */
     {
       
       /* blUdpTriggeringRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       0,
       
       /* blTcpTriggeringRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blMulticastEventSoConPresent */
       0,
       
       /* ucReserved */
       0
     }
   }
    };
      #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
      #include "Sd_MemMap.h" 

           
    #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
    #include "Sd_MemMap.h"
     CONST(Sd_ClientTimerStaticType, SD_CONST) Sd_GSaaClientTimerStatic[1] =
    {
   /* Sd_GSaaClientTimerStatic : 0 - SdInstance_0_SdClientTimer_0 */
   {
     
     /* ulClientTimerTtlsec */
     0xAU,
     
     /* ulInitialFindDelayMax */
     0x5,
     
     /* ulInitialFindDelayMin */
     0x5,
     
     /* ulInitialFindRepetitionsBaseDelay */
     0x0,
     
     /* ulRequestResponseMaxDelay */
     0x0,
     
     /* ulRequestResponseMinDelay */
     0x0,
     
     /* ucInitialFindRepetitionsMax */
     0x0,
     
     /* ulSubscribeEventgroupRetryDelay */
     0x0,
     
     /* ucSubscribeEventgroupRetryMax */
     0x2
   }
    };
    #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #include "Sd_MemMap.h" 
   

       
   #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
   #include "Sd_MemMap.h"
   CONST(Sd_ClientServiceStaticType, SD_CONST) Sd_GaaClientServiceStatic[4] =
   {
     /* Sd_GaaClientServiceStatic : 0 - SdInstance_0_SdClientService_0 */
     {
       
       /* usHandleId  */
       0x0,
       
       /* usServiceId */
       0x5U,
       
       /* usInstanceId */
       0x2U,
       
       /* ucMajorVersion */
       0x4,
       
       /* ulMinorVersion */
       0xC8U,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[4],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[5],
       
       /* pClientTimer */
       &Sd_GSaaClientTimerStatic[0],
       
       /* pConfigOption */
       &Sd_GSaaConfigurationOption[29],
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* usBaseConEventGrp */
       0x0,
       
       /* usNoOfConEventGrp */
       0x1,
       
       /* usClientSelfIndex */
       0x0,
       
       /* ddActivationRoGrpId */
       0x4,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /* stClientStaticFlag */
       {
         
         /* blAutoRequire */
         0,
         
         /* blActivationRoGrpIdPresent */
         1,
         
         /* ucReserved */
         0
       },
       
       /* EndrivenBehaviour */
       SD_EXACT_OR_ANY_MINOR_VERSION,
       
       /* usMaxNumOfIpAddressesInAcl */
        0,
       
       /* blAclEnable_Disable_Check */
        SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR,
       
       /* sdBlocklistedMinorVersions */
       0
     },
     /* Sd_GaaClientServiceStatic : 1 - SdInstance_0_SdClientService_1 */
     {
       
       /* usHandleId  */
       0x1,
       
       /* usServiceId */
       0xAU,
       
       /* usInstanceId */
       0x14U,
       
       /* ucMajorVersion */
       0x28,
       
       /* ulMinorVersion */
       0xFFFFFFFFU,
       
       /* pTcpSoConGrp */
       NULL_PTR,
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[3],
       
       /* pClientTimer */
       &Sd_GSaaClientTimerStatic[0],
       
       /* pConfigOption */
       &Sd_GSaaConfigurationOption[49],
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* usBaseConEventGrp */
       0x1,
       
       /* usNoOfConEventGrp */
       0x1,
       
       /* usClientSelfIndex */
       0x1,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /* stClientStaticFlag */
       {
         
         /* blAutoRequire */
         0,
         
         /* blActivationRoGrpIdPresent */
         0,
         
         /* ucReserved */
         0
       },
       
       /* EndrivenBehaviour */
       SD_EXACT_OR_ANY_MINOR_VERSION,
       
       /* usMaxNumOfIpAddressesInAcl */
        0,
       
       /* blAclEnable_Disable_Check */
        SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR,
       
       /* sdBlocklistedMinorVersions */
       0
     },
     /* Sd_GaaClientServiceStatic : 2 - SdInstance_0_SdClientService_2 */
     {
       
       /* usHandleId  */
       0x2,
       
       /* usServiceId */
       0xAU,
       
       /* usInstanceId */
       0x14U,
       
       /* ucMajorVersion */
       0x28,
       
       /* ulMinorVersion */
       0x64U,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[4],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[4],
       
       /* pClientTimer */
       &Sd_GSaaClientTimerStatic[0],
       
       /* pConfigOption */
       &Sd_GSaaConfigurationOption[67],
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* usBaseConEventGrp */
       0x2,
       
       /* usNoOfConEventGrp */
       0x1,
       
       /* usClientSelfIndex */
       0x2,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /* stClientStaticFlag */
       {
         
         /* blAutoRequire */
         0,
         
         /* blActivationRoGrpIdPresent */
         0,
         
         /* ucReserved */
         0
       },
       
       /* EndrivenBehaviour */
       SD_EXACT_OR_ANY_MINOR_VERSION,
       
       /* usMaxNumOfIpAddressesInAcl */
        0,
       
       /* blAclEnable_Disable_Check */
        SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR,
       
       /* sdBlocklistedMinorVersions */
       0
     },
     /* Sd_GaaClientServiceStatic : 3 - SdInstance_0_SdClientService_3 */
     {
       
       /* usHandleId  */
       0x3,
       
       /* usServiceId */
       0xAU,
       
       /* usInstanceId */
       0x14U,
       
       /* ucMajorVersion */
       0x28,
       
       /* ulMinorVersion */
       0x64U,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[4],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[4],
       
       /* pClientTimer */
       &Sd_GSaaClientTimerStatic[0],
       
       /* pConfigOption */
       &Sd_GSaaConfigurationOption[87],
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* usBaseConEventGrp */
       0x3,
       
       /* usNoOfConEventGrp */
       0x1,
       
       /* usClientSelfIndex */
       0x3,
       
       /* ddActivationRoGrpId */
       0x0,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /* stClientStaticFlag */
       {
         
         /* blAutoRequire */
         0,
         
         /* blActivationRoGrpIdPresent */
         0,
         
         /* ucReserved */
         0
       },
       
       /* EndrivenBehaviour */
       SD_EXACT_OR_ANY_MINOR_VERSION,
       
       /* usMaxNumOfIpAddressesInAcl */
        0,
       
       /* blAclEnable_Disable_Check */
        SD_FALSE,
       
       /* pServiceGroupRef */
       &Sd_GaaServicegroupStatic[0],
       
       /* sdBlocklistedMinorVersions */
       0
     }
   };
       
     #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
     #include "Sd_MemMap.h" 

       
    #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
    #include "Sd_MemMap.h"
    CONST(Sd_ConsumedEvGrpStaticType, SD_CONST) Sd_GaaConsumedEvGrpStatic[4] =
    {
   /* Sd_GaaConsumedEvGrpStatic : 
       	0 - SdInstance_0_SdClientService_0_SdConsumedEventGroup_0 */
   {
     
     /* pConfigOption */
     NULL_PTR,
     
     /* pClientTimer */
     &Sd_GSaaClientTimerStatic[0],
     
     /* usHandleId */
     0x0,
     
     /* usEventGroupId */
     0xF,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x5,
     
     /* ddTcpActivationRoGrpId */
     0x6,
     
     /* ddUdpActivationRoGrpId */
     0x7,
     
     /* ddBaseMulticastSoConGrp */
     0x0,
     
     /* ddNoOfMulticastSoConGrp */
     0x2,
     
     /* usClientServiceIndex */
     0x0,
     
     /* usConEvGrpSelfIndex */
     0x0,
     
     /* ucCounter */
     0x0,
     
     /* stConsumedEvGrpStaticFlag */
     {
       
       /* blAutoRequire */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       1,
       
       /* blTcpActivationRoGrpIdPresent */
       1,
       
       /* blUdpActivationRoGrpIdPresent */
       1,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaConsumedEvGrpStatic : 
       	1 - SdInstance_0_SdClientService_1_SdConsumedEventGroup_0 */
   {
     
     /* pConfigOption */
     NULL_PTR,
     
     /* pClientTimer */
     &Sd_GSaaClientTimerStatic[0],
     
     /* usHandleId */
     0x1,
     
     /* usEventGroupId */
     0x3C,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddBaseMulticastSoConGrp */
     0x0,
     
     /* ddNoOfMulticastSoConGrp */
     0x0,
     
     /* usClientServiceIndex */
     0x1,
     
     /* usConEvGrpSelfIndex */
     0x1,
     
     /* ucCounter */
     0x0,
     
     /* stConsumedEvGrpStaticFlag */
     {
       
       /* blAutoRequire */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       0,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaConsumedEvGrpStatic : 
       	2 - SdInstance_0_SdClientService_2_SdConsumedEventGroup_0 */
   {
     
     /* pConfigOption */
     NULL_PTR,
     
     /* pClientTimer */
     &Sd_GSaaClientTimerStatic[0],
     
     /* usHandleId */
     0x2,
     
     /* usEventGroupId */
     0x50,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddBaseMulticastSoConGrp */
     0x0,
     
     /* ddNoOfMulticastSoConGrp */
     0x0,
     
     /* usClientServiceIndex */
     0x2,
     
     /* usConEvGrpSelfIndex */
     0x2,
     
     /* ucCounter */
     0x0,
     
     /* stConsumedEvGrpStaticFlag */
     {
       
       /* blAutoRequire */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       1,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaConsumedEvGrpStatic : 
       	3 - SdInstance_0_SdClientService_3_SdConsumedEventGroup_0 */
   {
     
     /* pConfigOption */
     NULL_PTR,
     
     /* pClientTimer */
     &Sd_GSaaClientTimerStatic[0],
     
     /* usHandleId */
     0x3,
     
     /* usEventGroupId */
     0x50,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddBaseMulticastSoConGrp */
     0x0,
     
     /* ddNoOfMulticastSoConGrp */
     0x0,
     
     /* usClientServiceIndex */
     0x3,
     
     /* usConEvGrpSelfIndex */
     0x3,
     
     /* ucCounter */
     0x0,
     
     /* stConsumedEvGrpStaticFlag */
     {
       
       /* blAutoRequire */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       1,
       
       /* ucReserved */
       0
     }
   }
    };
      #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
      #include "Sd_MemMap.h" 

       
    #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
     #include "Sd_MemMap.h"
     CONST(Sd_SoConGroupStaticType, SD_CONST) Sd_GaaSoConGroupStatic[8] =
     {
   /*  Sd_GaaSoConGroupStatic : 0 - SoAdConfig_0_SoAdSocketConnectionGroup_0  */
   {
     
     /* usBaseSocketConIndex */
     0,
     
     /* usNoOfSockets */
      0x3 
   },
   /*  Sd_GaaSoConGroupStatic : 1 - SoAdConfig_0_SoAdSocketConnectionGroup_1  */
   {
     
     /* usBaseSocketConIndex */
     3,
     
     /* usNoOfSockets */
      0x2 
   },
   /*  Sd_GaaSoConGroupStatic : 2 - SoAdConfig_0_SoAdSocketConnectionGroup_2  */
   {
     
     /* usBaseSocketConIndex */
     5,
     
     /* usNoOfSockets */
      0x2 
   },
   /*  Sd_GaaSoConGroupStatic : 3 - SoAdConfig_0_SoAdSocketConnectionGroup_3  */
   {
     
     /* usBaseSocketConIndex */
     7,
     
     /* usNoOfSockets */
      0x1 
   },
   /*  Sd_GaaSoConGroupStatic : 4 - SoAdConfig_0_SoAdSocketConnectionGroup_4  */
   {
     
     /* usBaseSocketConIndex */
     8,
     
     /* usNoOfSockets */
      0x1 
   },
   /*  Sd_GaaSoConGroupStatic : 5 - SoAdConfig_0_SoAdSocketConnectionGroup_5  */
   {
     
     /* usBaseSocketConIndex */
     9,
     
     /* usNoOfSockets */
      0x2 
   },
   /*  Sd_GaaSoConGroupStatic : 6 - SoAdConfig_0_SoAdSocketConnectionGroup_6  */
   {
     
     /* usBaseSocketConIndex */
     11,
     
     /* usNoOfSockets */
      0x2 
   },
   /*  Sd_GaaSoConGroupStatic : 7 - SoAdConfig_0_SoAdSocketConnectionGroup_7  */
   {
     
     /* usBaseSocketConIndex */
     13,
     
     /* usNoOfSockets */
      0x2 
   }
    };
        #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
        #include "Sd_MemMap.h" 

       
   #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
   #include "Sd_MemMap.h"
   CONST(Sd_InstanceStaticType, SD_CONST) Sd_GaaInstanceStatic[2] =
   {
     /* Sd_GaaInstanceStatic : 0 - SdInstance_0 */
     {
       
       /* pConfigOption */
       &Sd_GSaaConfigurationOption[107],
       
       /* usBaseServerServiceIndex */
       0x0,
       
       /* usNoOfServerServices */
       0x6,
       
       /* usBaseClientServiceIndex  */
       0x0,
       
       /* usNoOfClientServices */
       0x4,
       
       /* ddTxPduId */
       0x0,
       
       /* ddUnicastRxPduId */
       0x2,
       
       /* ddMulticastRxPduId */
       0x1,
       
       /* ddIpAddrSoConId */
       0x0,
       
       /* ddRxUnicastSoConId */
       0x0,
       
       /* ddRxMulticastSoConId */
       0x0,
       
       /* usDemErrorMalformedId */
       0x1,
       
       /* usDemErrorOutOfResId */
       0x2,
       
       /* usDemErrorSubEventgroupNacId */
       SD_DEM_INVALID,
       
       /* ucInstanceSelfIndex */
       0x0,
       
       /* blDomainIpv4 */
       (boolean)SD_TRUE,
       
       /* usSdInstanceLocalAdressCheckLength */
       SD_INVALID
     },
     /* Sd_GaaInstanceStatic : 1 - SdInstance_1 */
     {
       
       /* pConfigOption */
       NULL_PTR,
       
       /* usBaseServerServiceIndex */
       0x6,
       
       /* usNoOfServerServices */
       0x2,
       
       /* usBaseClientServiceIndex  */
       0x0,
       
       /* usNoOfClientServices */
       0x0 ,
       
       /* ddTxPduId */
       0x3,
       
       /* ddUnicastRxPduId */
       0x3,
       
       /* ddMulticastRxPduId */
       0x0,
       
       /* ddIpAddrSoConId */
       0x1,
       
       /* ddRxUnicastSoConId */
       0x0,
       
       /* ddRxMulticastSoConId */
       0x0,
       
       /* usDemErrorMalformedId */
       0x2,
       
       /* usDemErrorOutOfResId */
       0x1,
       
       /* usDemErrorSubEventgroupNacId */
       SD_DEM_INVALID,
       
       /* ucInstanceSelfIndex */
       0x1,
       
       /* blDomainIpv4 */
       (boolean)SD_TRUE,
       
       /* usSdInstanceLocalAdressCheckLength */
       SD_INVALID
     }
   };
       
      #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
      #include "Sd_MemMap.h" 
   
         #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
         #include "Sd_MemMap.h"
          CONST(Sd_ServiceGroupType, SD_CONST)Sd_GaaServicegroupStatic[1] =
         {
        /* Sd_GaaServicegroupStatic  */
        {
          
          /* usHandleId */
          0x0
        }
         };
           #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
           #include "Sd_MemMap.h" 
  
#define SD_START_SEC_CONST_16
#include "Sd_MemMap.h"
 CONST(uint16, SD_CONST)Sd_GaaServicegroupClientArray[1][1] =
{
	
	{3}
};
#define SD_STOP_SEC_CONST_16
#include "Sd_MemMap.h" 
      
#define SD_START_SEC_CONST_16
#include "Sd_MemMap.h"
 CONST(uint16, SD_CONST)Sd_GaaServicegroupServerArray[1][1] =
{
	{7}
};
#define SD_STOP_SEC_CONST_16
#include "Sd_MemMap.h" 
 #define SD_START_SEC_CONST_UNSPECIFIED
 #include "Sd_MemMap.h"
  CONST(Sd_ServicegroupClientArrayType, SD_CONST)Sd_GaaServicegroupClientStatic[1] =
 {
/* Sd_GaaServicegroupClienttStatic  */
{
  
  /* usArray_size */
  1
}
 };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h" 
 #define SD_START_SEC_CONST_UNSPECIFIED
 #include "Sd_MemMap.h"
  CONST(Sd_ServicegroupServerArrayType, SD_CONST)Sd_GaaServicegroupServerStatic[1] =
 {
/* Sd_GaaServicegroupServerStatic  */
{
  
  /* usArray_size */
  1
}
 };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h" 
     
  
 
 
 
 
 
 
 
    

     
   
           

/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
