/*******************************************************************************
**  FILE-NAME: Sd_Cfg.h                                                     **
**                                                                            **
**  MODULE-NAME: Sd                                                           **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.1.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../TestAppl/App_Sd_All/PC_Config/xml/App_Sd_All.arxml
 *   ../../../171_Sd_DELIVERY/ssc/generator/KPIT_AUTOSAR_R24-11_SD_BSWMD.arxml
 *   ../../../171_Sd_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Wed 2025 Jul 02 19:00:22 IST
 */
#ifndef SD_CFG_H
#define SD_CFG_H

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
#include "SoAd.h"
#include "TcpIp_Types.h"

/*******************************************************************************
**                        Common Published Information                        **
*******************************************************************************/
#define SD_AR_RELEASE_MAJOR_VERSION    4
#define SD_AR_RELEASE_MINOR_VERSION    10
#define SD_AR_RELEASE_REVISION_VERSION 0
#define SD_SW_MAJOR_VERSION            0
#define SD_SW_MINOR_VERSION            1
#define SD_SW_PATCH_VERSION            0
#define SD_VENDOR_ID                   (uint16)39
#define SD_MODULE_ID                   (uint16)171

/*******************************************************************************
**                             Precompile Macros                              **
*******************************************************************************/
    /*  Pre-compile option for variant-support */
    #define SD_PRE_COMPILE_SINGLE                      STD_ON

    /* Pre-compile option for Error detection */
    #define SD_DEV_ERROR_DETECT                        STD_OFF

    /* Pre-compile option to check if Version Info API */
    #define SD_GET_VERSION_INFO                        STD_ON
    /* Pre-compile option to check if Version  */
    #define SD_SUBSCRIBE_EVENTGROUP_RETRY_ENABLE      STD_OFF
	   
	 /* Pre-compile option to check if Version  */
	 #define SD_ENABLE_ACL_POLICY_CHECK                STD_ON
	  	 

    
   /* Pre-compile option to check if SdSetRemAddrOfClientRxMulticastSoCon  */
   #define SD_SET_REM_ADDR_OF_CLIENT_RX_MULTICAST_SO_CON           STD_ON
    
	 #define SD_ENABLE_SECURITY_EVENT_REPORTING        STD_OFF



#define SD_DBTOC_VALUE                   0       

/*#define SD_SEV_SOME_IP_ACL_CHECK_FAILED_OFFER             84U */

 /*#define SD_SEV_DUPLICATE_OFFER             88U */
 
 /*#define SD_SEV_SOME_IP_ACL_CHECK_FAILED_EVENT_SUBSCRIPTION             85U */
   
/*#define SD_SEV_SOME_IP_ACL_CHECK_FAILED_METHOD_REQUEST             86U */
   /* Pre-compile option for SdMainFunctionCycleTime  */
   #define SD_SEC_TO_COUNT                               2U

   /* Pre-compile option for Total Instances across all ConfigSets */
   #define SD_NO_OF_INSTANCES                            2U

   /* Pre-compile option for Sd no of Server Services */
   #define SD_NO_OF_SERVER_SERVICES                      8U

   /* Pre-compile option for Sd no of Handles */
   #define SD_NO_OF_EV_HANDLERS                          5U

   /* Pre-compile option for Sd Queue size */
   #define SD_QUEUE_SIZE                                 21U

   /* Pre-compile option for Sd no of Client services */
   #define SD_NO_OF_CLIENT_SERVICES                      4U

   /* Pre-compile option for Sd no of Consumed EV Group */
   #define SD_NO_OF_CONSUMED_EV_GRP                      4U

   /* Pre-compile option for number of server timers */
   #define SD_NO_OF_SERVER_TIMERS                        2U
   
   /* Pre-compile option for number of client timers */
   #define SD_NO_OF_CLIENT_TIMERS                        1U

   /* Pre-compile option for no of socket groups */
   #define SD_NO_OF_SO_CON_GRPS                          8U

   /* Pre-compile option for Sd no of Socket connection */
   #define SD_NO_OF_SOCKET_CONNECTIONS                   15U
   
   /* Pre-compile option for Sd timer unused */
   #define SD_TIMER_UNUSED                               0U
   
   #define SD_SERVICE_GROUP        1U
   
   #define SD_NO_OF_ALLOWED_CLIENT_PROVIDER   0U
   
   #define SD_NO_OF_PROVIDED_SERVER_CONSUMER   0U

   /* Pre-compile option for Sd no of Multicast Group */
   #define SD_MULTICAST_GRP_INDEX_CONFIGURED             STD_ON

   /* Pre-compile option for Sd no of multicast socket connection group */
   #define SD_NO_OF_MULTICAST_SO_CON_GRP                 2U

   /* Pre-compile option for sd total size of config option */
   #define SD_TOTAL_SIZE_OF_CONFIG_OPTION                124U

   /* Pre-compile option for IPv6 */
   #define SD_IPV6_ENABLED                               STD_OFF

    /* Pre-compile option for if Consumed ev group is configured  is true */
    #define SD_CONSUMED_EV_GRP_CONFIGURED                 STD_ON
    
    /* Pre-compile option to check if Client is configured */
         #define SD_SERVICE_GROUP_CONFIGURED     STD_ON
         
    #define SD_CLIENT_REF_SERVICEGRP_CONFIGURED    1U
    #define SD_SERVER_REF_SERVICEGRP_CONFIGURED    1U
          

    /* Pre-compile option to check if Client is configured */
    #define SD_CLIENT_CONFIGURED                          STD_ON

    /* Pre-compile option to check if Ev handler is configured */
    #define SD_EV_HANDLER_CONFIGURED                      STD_ON

    /* Pre-compile option to check if server is configured */
    #define SD_SERVER_CONFIGURED                          STD_ON
    
    #define SD_NVMBLOCK_ID                  NULL_PTR
    
#define SD_RAM_BLOCK          STD_OFF
      
     
   #define SD_NVM_BLOCK_LENGTH (0U)
    #define SD_ROM_BLOCK          STD_OFF
      
     
      
    
    
    

/*******************************************************************************
**                                  Macros                                    **
*******************************************************************************/

/*******************************************************************************
**                             Global Data Types                              **
*******************************************************************************/
     
     
typedef uint8 Sd_ServicesType;
typedef uint16 Sd_TimeType;
/* ServerTimer
 * This is an array which contains all the Server Service Timers.
  All delay fields are in counts. count = (time in sec) /
                                            (main function period in sec)
  All Fields are configurable as per note given in the Sd_TimeType*/
/* Design_ID : SD_SDD_0123*/
typedef struct
{
  /* This is the SdServerTimerTTL in seconds */
  uint32 ulServerTimerTtlsec;
  /* This is the SdServerTimerInitialOfferDelayMax in counts */
  Sd_TimeType ulInitialOfferDelayMax;
  /* This is the SdServerTimerInitialOfferDelayMin in counts */
  Sd_TimeType ulInitialOfferDelayMin;
  /* This is the SdServerTimerInitialFindRepetitionsBaseDelay in counts */
  Sd_TimeType ulInitialOfferRepetitionBaseDelay;
  Sd_TimeType ulTimerOfferCyclicDelay;
  /* This is the SdServerTimerRequestResponseMaxDelay in counts */
  Sd_TimeType ulRequestResponseMaxDelay;
  /* This is the SdServerTimerRequestResponseMinDelay in counts */
  Sd_TimeType ulRequestResponseMinDelay;
  /* This is the SdServerTimerInitialFindRepetitionsMax (uint8) */
  uint8 ucInitialOfferRepetitionsMax;
} Sd_ServerTimerStaticType;
/* Design_ID : SD_SDD_0452*/
typedef struct
{
	 /*SdServiceGroupHandleId */
	uint16 usHandleId;
	
}Sd_ServiceGroupType;

/* Client Timer 
   This is an array which contains all the Client Service Timers.
  Most fields are in counts. count = (time in sec) /
                                      (main function period in sec)
  All Fields are configurable as per note given in the Sd_TimeType*/

/* Design_ID : SD_SDD_0117*/
typedef struct STag_Sd_ClientTimerStaticType
{
    /* This is the SdClientTimerTTL in seconds */
  uint32 ulClientTimerTtlsec;
    /* This is the SdClientTimerInitialFindDelayMax in counts */
  Sd_TimeType ulInitialFindDelayMax;
    /* This is the SdClientTimerInitialFindDelayMin in counts */
  Sd_TimeType ulInitialFindDelayMin;
    /* This is the SdClientTimerInitialFindRepetitionsBaseDelay in counts */
  Sd_TimeType ulInitialFindRepetitionsBaseDelay;
    /* This is the SdClientTimerRequestResponseMaxDelay in counts */
  Sd_TimeType ulRequestResponseMaxDelay;
    /* This is the SdClientTimerRequestResponseMinDelay in counts */
  Sd_TimeType ulRequestResponseMinDelay;
    /* This is the SdClientTimerInitialFindRepetitionsMax (uint8) */
  uint8 ucInitialFindRepetitionsMax;
  
  /* This is the SdSubscribeEventgroupRetryDelay in counts */
  Sd_TimeType ulSubscribeEventgroupRetryDelay;
  
 /* This is the SdSubscribeEventgroupRetryMax */
     uint8 ucSubscribeEventgroupRetryMax;
     
} Sd_ClientTimerStaticType;

/* SocketConnectionGroup
 * This is the SocketConnectionGroup Structure
  It contains all socketConnectiongroups referred to in all structures above */
/* Design_ID : SD_SDD_0127*/
typedef struct
{
    /* This is the base Id of the SocketConnection array. */
  SoAd_SoConIdType usBaseSocketConIndex;
    /* This is the no of sockets of the SocketConnection array. */
  uint16 usNoOfSockets;
} Sd_SoConGroupStaticType;


/* Instance Structure Static
 * Instance structure for static parameters */

/* Design_ID : SD_SDD_0123*/
typedef struct STag_Sd_InstanceStaticType
{
    /* This is pointer to the Configuration String containing hostname.
     * NULL if absent. */
  P2CONST(uint8, AUTOMATIC, SD_CONST) pConfigOption;
    /* Base Server Services Index (for Static and Dynamic arrays) */
  Sd_ServicesType usBaseServerServiceIndex;
    /* No of Server Sevices for this instance. */
  Sd_ServicesType usNoOfServerServices;
    /* Base Client Services Index (For Static and Dynamic arrays) */
  Sd_ServicesType usBaseClientServiceIndex;
    /* No of Client Services for this instance. */
  Sd_ServicesType usNoOfClientServices;
    /* The Tx PDU Id for this instance . Retrieved from SoAd -> SoAdPduRoute ->
     * SoAdTxPduId  that is matching with  SdTxPduRef*/
  PduIdType ddTxPduId;
    /* The Unicast Rx PduID for this instance  */
  PduIdType ddUnicastRxPduId;
    /* The Multicast RxPduId for this instance.  */
  PduIdType ddMulticastRxPduId;
    /* This is the SoConID that is used to check against the
     * Sd_LocalIpAddrAssignmentChg for this instance.  This SoConId is
     * referenced from the SoAdPduRoute -> SoAdTxPduRef, which has the same
     * value as SdInstanceTxPdu-> SdTxPduRef.
     * The value of the SoConId will be derived from SoAdPduRoute ->
     * SoAdPduRouteDest -> SoAdTxSocketConnOrSocketConnBundleRef.
     * If it is a group reference, the first SoConId in that group is
     * considered, else the SoCon is directly written.*/
  SoAd_SoConIdType ddIpAddrSoConId;
    /* Note - SoConId or SoConGrp needs to be generated here as per [00482] for
     * reception of message
     Pending Discussion. */
    /* Unicast SoConId derived as per [00482]  Pending Discussion */
  SoAd_SoConIdType ddRxUnicastSoConId;
    /* Multicast SoConId derived as per [00482]  Pending */
  SoAd_SoConIdType ddRxMulticastSoConId;
    /* This is the Dem ID of the error SD_E_MALFORMED_MSG, if not configured it
     * will have the value SD_DEM_INVALID*/
  uint16 usDemErrorMalformedId;
    /* This is the Dem ID of the error SD_E_OUT_OF_RES if not configured it
     * will have the value SD_DEM_INVALID */
  uint16 usDemErrorOutOfResId;
   /* Reference to the DemEventParameter which shall be issued when
    * receiving SubscribeEventgroupNack entry.*/
  uint16 usDemErrorSubEventgroupNackId;
    /* This is the self index for the instance */
  Sd_ServicesType ucInstanceSelfIndex;
  /* This is TRUE if domain is IPv4 and false if it is IPv6
    It is determined from the TCPIP domains of all the socketConnection Groups
    and PDU's associated with this instance. They must all be same */
  boolean blDomainIpv4;
  /*This item describes on how many bits of the addresses shall be compared to determine,
    if a remote address is acceptable to be used.
    This shall support IPv4 (0..32) and IPv6 (0..128).
    If this item is not present, the security checks use the configured netmask instead.
    "0" meaning not to check at all. For example "8" means that the first 8 bits of a remote
    address must be equal to the local address to be considered acceptable.*/
    uint16  usSdInstanceLocalAdressCheckLength;
} Sd_InstanceStaticType;

/* This is the Server Service Static Flag */
/* Design_ID : SD_SDD_0125*/
typedef struct STag_Sd_ServerStaticFlagType
{
    /* This is (1) if SdServerServiceAutoAvailable is TRUE else (0) */
  unsigned int blAutoAvaliable : 1;
    /*  This is (1) if SdServerServiceActivationRef is present else (0) */
  unsigned int blActivationRoGrpIdPresent : 1;
    /* Reserved */
  unsigned int ucReserved : 6;
} Sd_ServerStaticFlagType;
/*Service Group static */



/* Server Service Static
 * This is the structure for the Static parameters for the Server
  This is an array ordered as per configurations and then as per Instances.
*/

/* Design_ID : SD_SDD_0124*/
typedef  struct STag_Sd_ServerServiceStaticType
{
      /* This is the Minor Version for this Server Service. */
    uint32 ulMinorVersion;
      /* Reference Id of the SocketConnectionGroup Structure for TCP. NULL if
       * not present */
    P2CONST(Sd_SoConGroupStaticType, AUTOMATIC, SD_CONST) pTcpSoConGrp;
      /* Reference Id of the SocketConnectionGroup Structure for UDP. NULL if
       * not present */
    P2CONST(Sd_SoConGroupStaticType, AUTOMATIC, SD_CONST) pUdpSoConGrp;
      /* Reference to the Server Timer */
    P2CONST(Sd_ServerTimerStaticType, AUTOMATIC, SD_CONST) pServerTimer;
      /* This is pointer to the assembled Configuration option string. NULL if
       * absent. */
    P2CONST(uint8, AUTOMATIC, SD_CONST) pConfigOption;
      /* This is the Handle Id for the Server Service. */
    uint16 usHandleId;
      /* This is the Service ID for this Server Service. */
    uint16 usServiceId;
      /* This is Instance ID of the server service */
    uint16 usInstanceId;
      /* This is the Index of the key of the OtherServ option in the
       * ConfigurationOption array.  If OtherServ key is not present,
       * this is set as Zero */
    uint16 usOtherServKeyIndex;
      /* This is the Length of the the OtherServ key in the
       * ConfigurationOption array.  If OtherServ key is not present,
       * this is set as Zero */
    uint16 usOtherServKeyLength;
      /* This is the Routing Group ID  that is referred to in
       * SdServerServiceActivationRef in SdProvidedMethods */
    SoAd_RoutingGroupIdType ddActivationRoGrpId;
      /* The Base event handler index which is used by this server service */
    Sd_ServicesType usBaseEvHandlerIndex;
      /* No of Event Handlers registered to this server service.*/
    Sd_ServicesType usNoOfEvHandlers;
      /* This gives the index of the current element in the Server Service
       * array (Self Index)*/
    Sd_ServicesType usServerSelfIndex;
      /* This is the reference to the SdInstance for this ServerService */
    uint8 ucSdInstanceIndex;
      /* This is the Major Version for this ServerService. */
    uint8 ucMajorVersion;
      /* This is the flag for Server Static structure. (description below) */
    Sd_ServerStaticFlagType stServerStaticFlag;
    
   /*This is maximum number of address allowed in Acl list*/
   uint32 usMaxNumOfIpAddressesInAcl;
   
   boolean blAclEnable_Disable_Check;
    
	/*Sd_Service_grp_ref*/
	P2CONST(Sd_ServiceGroupType, AUTOMATIC, SD_CONST) pServiceGroupRef;
	
    
  
    
} Sd_ServerServiceStaticType;



/* This is the Event Handler Static Flag */
/* Design_ID : SD_SDD_0121*/
typedef struct STag_Sd_EvHandlerStaticFlagType
{
    /* This is TRUE if SdEventTriggeringRef in SdEventHandlerUdp is present */
  unsigned int blUdpTriggeringRoGrpIdPresent :1;
    /* This is TRUE if SdEventActivationRef in SdEventHandlerUdp is present */
  unsigned int blUdpActivationRoGrpIdPresent :1;
    /* This is TRUE if SdEventTriggeringRef in SdEventHandlerTcp is present */
  unsigned int blTcpTriggeringRoGrpIdPresent :1;
    /* This is TRUE if SdEventActivationRef in SdEventHandlerTcp is present */
  unsigned int blTcpActivationRoGrpIdPresent :1;
    /* This is TRUE if SdEventActivationRef in SdEventHandlerMulticast is
     * present */
  unsigned int blMulticastActivationRoGrpIdPresent :1;
    /* This is TRUE if SdMulticastEventSoConRef in SdEventHandlerMulticast
      is present */
  unsigned int blMulticastEventSoConPresent :1;
    /* Reserved */
  unsigned int ucReserved :2;
} Sd_EvHandlerStaticFlagType;


/* Event Handler Type Static
 * Array of structures ordered by Server Service.
  size is the total no of EvHandlers across all instances and all
  configurations */
/* Design_ID : SD_SDD_0122*/
typedef struct STag_Sd_EvHandlerStaticType
{
    /* Reference to Server Timer */
  P2CONST(Sd_ServerTimerStaticType, AUTOMATIC, SD_CONST) pServerTimer;
    /* This is pointer to the assembled Configuration option string. NULL if
     * absent. */
  P2CONST(uint8, AUTOMATIC, SD_CONST) pConfigOption;
    /* This is the SdEventHandlerHandleId */
  uint16 usHandleId;
    /* This is the SdEventHandlerEventGroupId */
  uint16 usEventGroupId;
    /* This is the SdEventHandlerMulticastThreshold */
  uint16 usMulticastThreshold;
    /* This is the Index of the key of the OtherServ option in the
     * ConfigurationOption array.  If OtherServ key is not present,
     * this is set as Zero */
  uint16 usOtherServKeyIndex;
    /* This is the Length of the the OtherServ key in the
     * ConfigurationOption array.  If OtherServ key is not present,
     * this is set as Zero */
  uint16 usOtherServKeyLength;
    /* This is the Routing Group Id mentioned in SdEventHandlerUdp ->
     * SdEventTriggeringRef */
  SoAd_RoutingGroupIdType ddUdpTriggeringRoGrpId;
    /* This is the Routing Group Id mentioned in SdEventHandlerUdp ->
     * SdEventActivationRef */
  SoAd_RoutingGroupIdType ddUdpActivationRoGrpId;
    /* This is the Routing Group Id mentioned in SdEventHandlerTcp ->
     * SdEventTriggeringRef */
  SoAd_RoutingGroupIdType ddTcpTriggeringRoGrpId;
    /* This is the Routing Group Id mentioned in SdEventHandlerTcp ->
     * SdEventActivationRef */
  SoAd_RoutingGroupIdType ddTcpActivationRoGrpId;
    /* This is the Routing Group Id mentioned in SdEventHandlerMulticast ->
     * SdEventActivationRef */
  SoAd_RoutingGroupIdType ddMulticastActivationRoGrpId;
    /* This is the Socket Connection ID referred to in
            SdEventHandlerMulticast -> SdMulticastEventSoConRef */
  SoAd_SoConIdType ddMulticastEventSoConId;
    /* Index of the Reference to Server Service */
  Sd_ServicesType usServerServiceIndex;
    /* This gives the index of the current element in the Event Handler array
     * (Self Index)*/
  Sd_ServicesType usEvHandlerSelfIndex;
    /* This is the flag for the Event Handler */
  Sd_EvHandlerStaticFlagType stEvHandlerStaticFlag;
} Sd_EvHandlerStaticType;



/* This is the flag for the Client service static */
/* Design_ID : SD_SDD_0115*/
typedef struct STag_Sd_ClientServiceStaticFlagType
{
    /* This is (1) if  SdClientServiceAutoRequire is TRUE else (0) */
  unsigned int blAutoRequire :1;
    /* This is (1) if SdClientServiceActivationRef in SdConsumedMethods is
     * configured else (0) */
  unsigned int blActivationRoGrpIdPresent : 1;
    /* Reserved */
  unsigned int ucReserved :6;
} Sd_ClientServiceStaticFlagType;
/*SdVersionDrivenFindBehavior enumerationtype*/
typedef enum ETag_Sd_VersionDrivenFindBehavior
{
	SD_EXACT_OR_ANY_MINOR_VERSION = 0,
	SD_MINIMUM_MINOR_VERSION
}Sd_VersionDrivenFindBehaviorType;

/* Client Service Static
 * This contains the static parameters for client service */
/* Design_ID : SD_SDD_0116*/
typedef struct STag_Sd_ClientServiceStaticType
{
    /* This is the Handle Id for the Client Service*/
   uint16 usHandleId;
    /* This is the Service ID for the Client Service */
  uint16 usServiceId;
    /* This is the Instance ID for the Client Service */
  uint16 usInstanceId;
    /* This is the Major Version for the Client Service. */
  uint8 ucMajorVersion;
    /* This is the Minor Version for the Client Service */
  uint32 ulMinorVersion;

    /* Reference Id of the SocketConnectionGroup Structure for TCP. NULL if no
     * present */
  P2CONST(Sd_SoConGroupStaticType, AUTOMATIC, SD_CONST) pTcpSoConGrp;
    /* Reference Id of the SocketConnectionGroup Structure for UDP. NULL if not
     * present */
  P2CONST(Sd_SoConGroupStaticType, AUTOMATIC, SD_CONST) pUdpSoConGrp;
    /* Reference to the Client Timer */
  P2CONST(Sd_ClientTimerStaticType, AUTOMATIC, SD_CONST) pClientTimer;
    /* This is pointer to the assembled Configuration option string. NULL if
     * absent. */
  P2CONST(uint8, AUTOMATIC, SD_CONST) pConfigOption;
    /* This is the Index of the key of the OtherServ option in the
     * ConfigurationOption array.  If OtherServ key is not present,
     * this is set as Zero */
  uint16 usOtherServKeyIndex;
    /* This is the Length of the the OtherServ key in the
     * ConfigurationOption array.  If OtherServ key is not present,
     * this is set as Zero */
  uint16 usOtherServKeyLength;
    /* This is the base Consumed Event Group for this Client Service */
  Sd_ServicesType usBaseConEventGrp;
    /* This is the no of Consumed Event Groups for this Client Service */
  Sd_ServicesType usNoOfConEventGrp;
    /* This gives the index of the current element in the Client Service array
    (Self Index)*/
  Sd_ServicesType usClientSelfIndex;
    /* This is the Routing Group ID  that is referred to in
     * SdClientServiceActivationRef in SdConsumedMethods */
  SoAd_RoutingGroupIdType ddActivationRoGrpId;
    /* This is the reference to the SdInstance for this ServerService */
  uint8 ucSdInstanceIndex;
    /* Flag for Client Service Static */
  Sd_ClientServiceStaticFlagType stClientStaticFlag;
  /* Version driver behaviour */
  Sd_VersionDrivenFindBehaviorType EndrivenBehaviour;
  
   /*This is maximum number of address allowed in Acl list*/
     uint32 usMaxNumOfIpAddressesInAcl;
     
     boolean blAclEnable_Disable_Check;
  
  /*Sd_Service_Group_Ref*/
  P2CONST(Sd_ServiceGroupType, AUTOMATIC, SD_CONST) pServiceGroupRef;
  
  uint16 SdBlacklistedMinorVersions;
  
 
} Sd_ClientServiceStaticType;


/* This is the flag for consumed event group static parameters */
/* Design_ID : SD_SDD_0119*/
typedef struct STag_Sd_ConsumedEvGrpStaticFlagType
{
    /* This is set to (1) if SdConsumedEventGroupAutoRequire is TRUE else (0) */
  unsigned int blAutoRequire :1;
    /* This is TRUE if SdConsumedEventGroupMulticastActivationRef is present */
  unsigned int blMulticastActivationRoGrpIdPresent :1;
    /* This is TRUE if SdConsumedEventGroupTcpActivationRef is present */
  unsigned int blTcpActivationRoGrpIdPresent :1;
    /* This is TRUE if SdConsumedEventGroupUdpActivationRef is present */
  unsigned int blUdpActivationRoGrpIdPresent :1;
    /* Reserved */
  unsigned int ucReserved:4;
} Sd_ConsumedEvGrpStaticFlagType;




/* Consumed Event Group Static
   This is the structure to hold the consumed event group static constants
 It is an array of size the total no of consumed event groups .
It is indexed according to the Sd_ClientServiceStaticType structure */
/* Design_ID : SD_SDD_0120*/
/* Design_ID : SD_SDD_0010*/
typedef struct STag_Sd_ConsumedEvGrpStaticType
{
    /* This is pointer to the assembled Configuration option string. NULL if
     * absent. */
  P2CONST(uint8, AUTOMATIC, SD_CONST) pConfigOption;
    /* Reference to the Client Timer */
  P2CONST(Sd_ClientTimerStaticType, AUTOMATIC, SD_CONST) pClientTimer;
    /* This is the Handle Id for the Consumed Event Grp */
  uint16 usHandleId;
    /* This is the Event Group ID as configured */
  uint16 usEventGroupId;
    /* This is the Index of the key of the OtherServ option in the
     * ConfigurationOption array.  If OtherServ key is not present,
     * this is set as Zero */
  uint16 usOtherServKeyIndex;
    /* This is the Length of the the OtherServ key in the
     * ConfigurationOption array.  If OtherServ key is not present,
     * this is set as Zero */
  uint16 usOtherServKeyLength;
    /* This is the Routing Group Id mentioned in
     * SdConsumedEventGroupMulticastActivationRef */
  SoAd_RoutingGroupIdType ddMulticastActivationRoGrpId;
    /* This is the Routing Group Id mentioned in
     * SdConsumedEventGroupTcpActivationRef */
  SoAd_RoutingGroupIdType ddTcpActivationRoGrpId;
    /* This is the Routing Group Id mentioned in
     * SdConsumedEventGroupUdpActivationRef */
  SoAd_RoutingGroupIdType ddUdpActivationRoGrpId;
    /* This is the base index of the first SoConGrp refeerred by
     * SdConsumedEventGroupMulticastGroupRef */
  SoAd_SoConIdType ddBaseMulticastSoConGrpIndex;
    /* This is the number of SdConsumedEventGroupMulticastGroupRef */
  SoAd_SoConIdType ddNoOfMulticastSoConGrp;
    /* This is the Client Service Index for this Consumed Event Group */
  Sd_ServicesType usClientServiceIndex;
    /* This gives the index of the current element in the Consumed Event
     * Group array (Self Index)*/
  Sd_ServicesType usConEvGrpSelfIndex;
    /* This field is generated if multiple Consumed event groups in the same
     * ClientService have the same EventGroupId. For the first one, it is
     * generated as 0, for the second as 1, and so on.  This counter has a
     * range from 0 to 15*/
  uint8 ucCounter;
    /* Flag for the Consumed Event Group */
  Sd_ConsumedEvGrpStaticFlagType stConsumedEvGrpStaticFlag;
} Sd_ConsumedEvGrpStaticType;



/* Design_ID : SD_SDD_0453*/
typedef struct STag_Sd_ServicegroupClientArrayType
{
  
  uint16 usArray_size;
    /* This is the Event Group ID as configured */
 
 
} Sd_ServicegroupClientArrayType;
/* Design_ID : SD_SDD_0454*/
typedef struct STag_Sd_ServicegroupServerArrayType
{
  
  uint16 usArray_size;
    /* This is the Event Group ID as configured */
 
 
} Sd_ServicegroupServerArrayType;

typedef enum ETag_Sd_IpAddressType
{
		SD_AF_INET = 2,
		SD_AF_INET6 = 28,
		SD_WILDCARD_DOMAIN = 0, 
		
}Sd_IpAddressType;
	
typedef enum ETag_Sd_ProviderConsumerType
{    
	SD_CONSUMER_TYPE,
	SD_PROVIDER_TYPE,
	SD_ANY_TYPE
	
}Sd_ProviderConsumerType;

typedef struct STag_Sd_ProviderConsumerList
{
	uint16 usServiceId;
	
	Sd_ProviderConsumerType ListMemberType;
	
	Sd_IpAddressType domain;

	uint8 SdIpAddress[18];
	
}Sd_ProviderConsumerListType;



/*SD_SDD_0118*/
/* config structure */
typedef struct STag_Sd_ConfigType
{
  uint8 ucdummy;
}Sd_ConfigType;



/*******************************************************************************
**                         Configuration Set Handles                          **
*******************************************************************************/

/*******************************************************************************
**                            Function Prototypes                             **
*******************************************************************************/

#endif /* SD_CFG_H */
/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
