/*******************************************************************************
**  FILE-NAME: Sd_Cfg.c                                                     **
**                                                                            **
**  MODULE-NAME: Sd                                                           **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.3.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ECUConfiguration.arxml
 *
 * GENERATED ON : Tue 2026 May 05 11:44:41 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
         /*******************************************************************************
         **                   MISRA-C:2012 violations Section                          **
         *******************************************************************************/
         /**
         * #page misra_violations MISRA-C:2012 violations
         *
         * #section Sd_Cfg_C_REF_1
         * Violates MISRA 2012 Advisory Rule 20.1, #include directives should only be
         * preceded by preprocessor directives or comments
         *
         * #section Sd_Cfg_C_REF_2
         * Violates MISRA 2012 Required Dir-1.1, [L] Number of macro definitions exceeds
         * 4095 - program does not conform strictly to ISO:C99.
         **/
         /*#violates #ref Sd_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 20.1*/
         /*PRQA S 5087 EOF */
         /* violates #ref Sd_Cfg_C_REF_2 Violates MISRA 2012 Dir-1.1 */
         /* PRQA S 0380 EOF */
         
         /** #section Sd_Cfg_C_REF_1
             * Violates MISRA 2012 Advisory Rule 20.1,
             * #include directives should only be preceded by preprocessor directives or
             * comments.
             *
             **/
             
            /**
              *
              * #section Sd_Cfg_C_REF_1
              * Violates MISRA 2012 Advisory Rule 1.1,
              * Number of Macro definitions exceed 1024.
              *
              **/
              
            /* Violates #ref Sd_Cgf_C_REF_1 Violates MISRA 2012 Required Rule 20.1 */
            /* PRQA S 5087 EOF */
                #include "Sd_Cfg.h"
            /* Violates #ref Sd_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 1.1 */
            /* PRQA S 0857 EOF */
        /* Violates #ref Sd_Cfg_C_REF_2 Violates INT02 Msg(qac-10.1.0-1290) */
            /*PRQA S 1290 EOF*/
		/* Violates #ref Sd_Cfg_C_REF_2 Violates INT02 DCL06,EXP07 Msg(qac-10.1.0-3132) */
		/*PRQA S 3132 EOF*/
		/* #Violates #ref SD_Cfg_C_REF_2 PRE08 Msg(certccm-2.1.0-5002)  */
            /*PRQA S 5002 EOF*/
		/* #Violates #ref SD_Cfg_REF_2 CMN-0:CMN-0.1,CMN-0.1 Msg(qac-10.1.0-4810)  */
           
      /* #Violates #ref SD_Cfg_REF_2 CMN-0:CMN-0.1,CMN-0.1 Msg(qac-10.1.0-4810)  */
             /*PRQA S 4810 EOF */
/*#Violates #ref SD_Cfg_REF_2 CMN-0:CMN-0.1,CMN-0.1   M3CM-2:Rule-9.3 Msg(qac-10.1.0-0686)*/
         /*PRQA S 0686 EOF */
         
         
         /******************************************************************************/
             #include "Sd.h"
             #include "Sd_IntTypes.h"
             #include "Sd_Internal.h"
             #include "Sd_Version.h"
         

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (SD_VERSION_AR_RELEASE_MAJOR_VERSION != SD_AR_RELEASE_MAJOR_VERSION)
  #error "SD Code : Mismatch in Specification Major Version"
#endif

#if (SD_VERSION_AR_RELEASE_MINOR_VERSION != SD_AR_RELEASE_MINOR_VERSION)
  #error "SD Code : Mismatch in Specification Minor Version"
#endif

#if (SD_VERSION_AR_RELEASE_REVISION_VERSION != SD_AR_RELEASE_REVISION_VERSION)
  #error "SD Code : Mismatch in Specification Revision Version"
#endif

#if (SD_VERSION_SW_MAJOR_VERSION != SD_SW_MAJOR_VERSION)
  #error "SD Code : Mismatch in Software Major Version"
#endif

#if (SD_VERSION_SW_MINOR_VERSION != SD_SW_MINOR_VERSION)
  #error "SD Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/
   
   #if (SD_RAM_BLOCK == STD_ON)
   #define SD_START_SEC_VAR_NO_INIT_UNSPECIFIED
   #include "Sd_MemMap.h"
   Sd_ProviderConsumerListType Sd_GaaClient_Server_List[SD_NO_OF_RAM_ALLOWED_SERVER_CLIENT_PROVIDER_CONSUMER];
   #define SD_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
   #include "Sd_MemMap.h"
   #endif
       
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaServerHandleMapArray */
   const Sd_ServicesType Sd_GaaServerHandleMapArray[2] = {
        1,
        0
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

       
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaClientHandleMapArray */
   const Sd_ServicesType Sd_GaaClientHandleMapArray[1] = {
     0
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

       
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaConEvGrpHandleMapArray */
   const Sd_ServicesType Sd_GaaConEvGrpHandleMapArray[3] = {
     0,
     1,
     2
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

       
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaRxPduMapArray */
   const Sd_ServicesType Sd_GaaRxPduMapArray[2] = {
   0,
   0
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

       
   

        
   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   /* Sd_GaaSoConId */
   const SoAd_SoConIdType Sd_GaaSoConId[12] = 
   {
     6,     7,     8,     9,     20,     22,     21,     30,     31,     11,     25,     10
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"

       

        
   #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
   #include "Sd_MemMap.h"
   static const Sd_ServerTimerStaticType Sd_GSaaServerTimerStatic[1] =
   {
     /* Sd_GSaaServerTimerStatic_0 - SdInstance_0_PSI_EnhancedTestabilityServiceLow_Timer */
     {
       
       /* ulServerTimerTtlsec */
       0x3U,
       
       /* ulInitialOfferDelayMax */
        0x1,
       
       /* ulInitialOfferDelayMin */
       0x1,
       
       /* ulInitialOfferRepetitionBaseDelay */
       0x3,
       
       /* ulTimerOfferCyclicDelay */
       0x1F4,
       
       /* ulRequestResponseMaxDelay */
       0x1,
       
       /* ulRequestResponseMinDelay */
        0x1,
       
       /*  ucInitialOfferRepetitionsMax  */
        0x3
     }
   };
    #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #include "Sd_MemMap.h" 

       
   #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
   #include "Sd_MemMap.h"
   const Sd_ServerServiceStaticType Sd_GaaServerServiceStatic[2] =
   {
     /* Sd_GaaServerServiceStatic : 0 - SdInstance_0_PSI_EngineManagementSystem */
     {
       
       /* ulMinorVersion */
       0x0U,
       
       /* pTcpSoConGrp */
       &Sd_GaaSoConGroupStatic[1],
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[2],
       
       /* pServerTimer */
       &Sd_GSaaServerTimerStatic[0],
       
       /* pConfigOption */
       NULL_PTR,
       
       /*  usHandleId */
       0x1,
       
       /* usServiceId */
       0x104U,
       
       /* usInstanceId */
       0x1,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* ddActivationRoGrpId */
       0x7,
       
       /* usBaseEvHandlerIndex */
       0x0,
       
       /* usNoOfEvHandlers */
       0x1,
       
       /* usServerSelfIndex */
       0x0,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /*  ucMajorVersion */
       0x1,
       
       /* stServerStaticFlag */
       {
         
         /* blAutoAvaliable */
         0,
         
         /* blActivationRoGrpIdPresent */
         1,
         
         /* ucReserved  */
         0
       },
       
       /* usMaxNumOfIpAddressesInAcl */
       2,
       
       /* blAclEnable_Disable_Check */
       SD_TRUE,
       
       /* pServiceGroupRef */
       NULL_PTR
     },
     /* Sd_GaaServerServiceStatic : 1 - SdInstance_0_PSI_EnhancedTestabilityServiceLow */
     {
       
       /* ulMinorVersion */
       0x0U,
       
       /* pTcpSoConGrp */
       NULL_PTR,
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[3],
       
       /* pServerTimer */
       &Sd_GSaaServerTimerStatic[0],
       
       /* pConfigOption */
       NULL_PTR,
       
       /*  usHandleId */
       0x0,
       
       /* usServiceId */
       0x103U,
       
       /* usInstanceId */
       0x7D,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* ddActivationRoGrpId */
       0x3,
       
       /* usBaseEvHandlerIndex */
       0x1,
       
       /* usNoOfEvHandlers */
       0x3,
       
       /* usServerSelfIndex */
       0x1,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /*  ucMajorVersion */
       0x1,
       
       /* stServerStaticFlag */
       {
         
         /* blAutoAvaliable */
         0,
         
         /* blActivationRoGrpIdPresent */
         1,
         
         /* ucReserved  */
         0
       },
       
       /* usMaxNumOfIpAddressesInAcl */
       0,
       
       /* blAclEnable_Disable_Check */
       SD_FALSE,
       
       /* pServiceGroupRef */
       NULL_PTR
     }
   };
       
      #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
      #include "Sd_MemMap.h" 

       
    #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
    #include "Sd_MemMap.h"
    const Sd_EvHandlerStaticType Sd_GaaEvHandlerStatic[4] =
    {
   /* Sd_GaaEvHandlerStatic : 
       	0 - SdInstance_0_PSI_EngineManagementSystem_PSI_EngineManagementSystem_EventGroupId_0x1001 */
   {
     
     /* pServerTimer */
     &Sd_GSaaServerTimerStatic[1],
     
     /* pConfigOption */
     NULL_PTR,
     
     /* usHandleId */
     0x3,
     
     /* usEventGroupId */
     0x1U,
     
     /* usMulticastThreshold */
     0x0,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddUdpTriggeringRoGrpId */
     0x7,
     
     /* ddUdpActivationRoGrpId */
     0x7,
     
     /* ddTcpTriggeringRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x7,
     
     /* ddMulticastActivationRoGrpId */
     0x8,
     
     /* ddMulticastEventSoConId */
     0x16,
     
     /* usServerServiceIndex */
     0x0,
     
     /* usEvHandlerSelfIndex */
     0x0,
     
     /* stEvHandlerStaticFlag */
     {
       
       /* blUdpTriggeringRoGrpIdPresent */
       1,
       
       /* blUdpActivationRoGrpIdPresent */
       1,
       
       /* blTcpTriggeringRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       1,
       
       /* blMulticastActivationRoGrpIdPresent */
       1,
       
       /* blMulticastEventSoConPresent */
       1,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaEvHandlerStatic : 
       	1 - SdInstance_0_PSI_EnhancedTestabilityServiceLow_PSI_EnhancedTestabilityServiceLow_EventGroupId_2 */
   {
     
     /* pServerTimer */
     &Sd_GSaaServerTimerStatic[1],
     
     /* pConfigOption */
     NULL_PTR,
     
     /* usHandleId */
     0x0,
     
     /* usEventGroupId */
     0x2U,
     
     /* usMulticastThreshold */
     0x0,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddUdpTriggeringRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x3,
     
     /* ddTcpTriggeringRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x2,
     
     /* ddMulticastEventSoConId */
     0xA,
     
     /* usServerServiceIndex */
     0x1,
     
     /* usEvHandlerSelfIndex */
     0x1,
     
     /* stEvHandlerStaticFlag */
     {
       
       /* blUdpTriggeringRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       1,
       
       /* blTcpTriggeringRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       1,
       
       /* blMulticastEventSoConPresent */
       1,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaEvHandlerStatic : 
       	2 - SdInstance_0_PSI_EnhancedTestabilityServiceLow_PSI_EnhancedTestabilityServiceLow_EventGroupId_5 */
   {
     
     /* pServerTimer */
     &Sd_GSaaServerTimerStatic[2],
     
     /* pConfigOption */
     NULL_PTR,
     
     /* usHandleId */
     0x1,
     
     /* usEventGroupId */
     0x5U,
     
     /* usMulticastThreshold */
     0x0,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddUdpTriggeringRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x3,
     
     /* ddTcpTriggeringRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x2,
     
     /* ddMulticastEventSoConId */
     0xA,
     
     /* usServerServiceIndex */
     0x1,
     
     /* usEvHandlerSelfIndex */
     0x2,
     
     /* stEvHandlerStaticFlag */
     {
       
       /* blUdpTriggeringRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       1,
       
       /* blTcpTriggeringRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       1,
       
       /* blMulticastEventSoConPresent */
       1,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaEvHandlerStatic : 
       	3 - SdInstance_0_PSI_EnhancedTestabilityServiceLow_PSI_EnhancedTestabilityServiceLow_EventGroupId_6 */
   {
     
     /* pServerTimer */
     &Sd_GSaaServerTimerStatic[3],
     
     /* pConfigOption */
     NULL_PTR,
     
     /* usHandleId */
     0x2,
     
     /* usEventGroupId */
     0x6U,
     
     /* usMulticastThreshold */
     0x0,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddUdpTriggeringRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x3,
     
     /* ddTcpTriggeringRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x2,
     
     /* ddMulticastEventSoConId */
     0xA,
     
     /* usServerServiceIndex */
     0x1,
     
     /* usEvHandlerSelfIndex */
     0x3,
     
     /* stEvHandlerStaticFlag */
     {
       
       /* blUdpTriggeringRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       1,
       
       /* blTcpTriggeringRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       1,
       
       /* blMulticastEventSoConPresent */
       1,
       
       /* ucReserved */
       0
     }
   }
    };
      #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
      #include "Sd_MemMap.h" 

           
    #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
    #include "Sd_MemMap.h"
     const Sd_ClientTimerStaticType Sd_GSaaClientTimerStatic[4] =
    {
   /* Sd_GSaaClientTimerStatic : 0 - SdInstance_0_CSI_EnhancedTestabilityServiceLow_Timer */
   {
     
     /* ulClientTimerTtlsec */
     0xE10U,
     
     /* ulInitialFindDelayMax */
     0x64,
     
     /* ulInitialFindDelayMin */
     0x0,
     
     /* ulInitialFindRepetitionsBaseDelay */
     0x3,
     
     /* ulRequestResponseMaxDelay */
     0x1,
     
     /* ulRequestResponseMinDelay */
     0x1,
     
     /* ucInitialFindRepetitionsMax */
     0x3,
     
     /* ulSubscribeEventgroupRetryDelay */
     SD_TIMER_UNUSED,
     
     /* ucSubscribeEventgroupRetryMax */
     SD_TIMER_UNUSED
   },
   /* Sd_GSaaClientTimerStatic : 1 - SdInstance_0_CSI_EnhancedTestabilityServiceLow_EventGroupId_2_Timer */
   {
     
     /* ulClientTimerTtlsec */
     0x3U,
     
     /* ulInitialFindDelayMax */
     0x1,
     
     /* ulInitialFindDelayMin */
     0x1,
     
     /* ulInitialFindRepetitionsBaseDelay */
     0x3,
     
     /* ulRequestResponseMaxDelay */
     0x1,
     
     /* ulRequestResponseMinDelay */
     0x1,
     
     /* ucInitialFindRepetitionsMax */
     0x3,
     
     /* ulSubscribeEventgroupRetryDelay */
     0x32,
     
     /* ucSubscribeEventgroupRetryMax */
     0x2
   },
   /* Sd_GSaaClientTimerStatic : 2 - SdInstance_0_CSI_EnhancedTestabilityServiceLow_EventGroupId_5_Timer */
   {
     
     /* ulClientTimerTtlsec */
     0x3U,
     
     /* ulInitialFindDelayMax */
     SD_TIMER_UNUSED,
     
     /* ulInitialFindDelayMin */
     SD_TIMER_UNUSED,
     
     /* ulInitialFindRepetitionsBaseDelay */
     SD_TIMER_UNUSED,
     
     /* ulRequestResponseMaxDelay */
     0x1,
     
     /* ulRequestResponseMinDelay */
     0x1,
     
     /* ucInitialFindRepetitionsMax */
     SD_TIMER_UNUSED,
     
     /* ulSubscribeEventgroupRetryDelay */
     SD_TIMER_UNUSED,
     
     /* ucSubscribeEventgroupRetryMax */
     SD_TIMER_UNUSED
   },
   /* Sd_GSaaClientTimerStatic : 3 - SdInstance_0_CSI_EnhancedTestabilityServiceLow_EventGroupId_6_Timer */
   {
     
     /* ulClientTimerTtlsec */
     0x3U,
     
     /* ulInitialFindDelayMax */
     SD_TIMER_UNUSED,
     
     /* ulInitialFindDelayMin */
     SD_TIMER_UNUSED,
     
     /* ulInitialFindRepetitionsBaseDelay */
     SD_TIMER_UNUSED,
     
     /* ulRequestResponseMaxDelay */
     0x1,
     
     /* ulRequestResponseMinDelay */
     0x1,
     
     /* ucInitialFindRepetitionsMax */
     SD_TIMER_UNUSED,
     
     /* ulSubscribeEventgroupRetryDelay */
     SD_TIMER_UNUSED,
     
     /* ucSubscribeEventgroupRetryMax */
     SD_TIMER_UNUSED
   }
    };
    #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #include "Sd_MemMap.h" 
   

       
   #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
   #include "Sd_MemMap.h"
   const Sd_ClientServiceStaticType Sd_GaaClientServiceStatic[1] =
   {
     /* Sd_GaaClientServiceStatic : 0 - SdInstance_0_CSI_EnhancedTestabilityServiceLow */
     {
       
       /* usHandleId  */
       0x0,
       
       /* usServiceId */
       0x103U,
       
       /* usInstanceId */
       0xABCDU,
       
       /* ucMajorVersion */
       0x1,
       
       /* ulMinorVersion */
       0xFFFFFFFFU,
       
       /* pTcpSoConGrp */
       NULL_PTR,
       
       /* pUdpSoConGrp */
       &Sd_GaaSoConGroupStatic[0],
       
       /* pClientTimer */
       &Sd_GSaaClientTimerStatic[0],
       
       /* pConfigOption */
       NULL_PTR,
       
       /* usOtherservKeyIndex */
       0x0,
       
       /* usOtherservKeyLength */
       0x0,
       
       /* usBaseConEventGrp */
       0x0,
       
       /* usNoOfConEventGrp */
       0x3,
       
       /* usClientSelfIndex */
       0x0,
       
       /* ddActivationRoGrpId */
       0x1,
       
       /* ucSdInstanceIndex */
       0x0,
       
       /* stClientStaticFlag */
       {
         
         /* blAutoRequire */
         0,
         
         /* blActivationRoGrpIdPresent */
         1,
         
         /* ucReserved */
         0
       },
       
       /* EndrivenBehaviour */
       SD_EXACT_OR_ANY_MINOR_VERSION,
       
       /* usMaxNumOfIpAddressesInAcl */
       2,
       
       /* blAclEnable_Disable_Check */
       SD_TRUE,
       
       /* pServiceGroupRef */
       NULL_PTR,
       
       /* sdBlocklistedMinorVersions */
       0
     }
   };
       
     #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
     #include "Sd_MemMap.h" 

       
    #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
    #include "Sd_MemMap.h"
    const Sd_ConsumedEvGrpStaticType Sd_GaaConsumedEvGrpStatic[3] =
    {
   /* Sd_GaaConsumedEvGrpStatic : 
       	0 - SdInstance_0_CSI_EnhancedTestabilityServiceLow_CSI_EnhancedTestabilityServiceLow_EventGroupId_2 */
   {
     
     /* pConfigOption */
     NULL_PTR,
     
     /* pClientTimer */
     &Sd_GSaaClientTimerStatic[1],
     
     /* usHandleId */
     0x0,
     
     /* usEventGroupId */
     0x2,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddBaseMulticastSoConGrp */
     0x0,
     
     /* ddNoOfMulticastSoConGrp */
     0x0,
     
     /* usClientServiceIndex */
     0x0,
     
     /* usConEvGrpSelfIndex */
     0x0,
     
     /* ucCounter */
     0x0,
     
     /* stConsumedEvGrpStaticFlag */
     {
       
       /* blAutoRequire */
       1,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       0,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaConsumedEvGrpStatic : 
       	1 - SdInstance_0_CSI_EnhancedTestabilityServiceLow_CSI_EnhancedTestabilityServiceLow_EventGroupId_5 */
   {
     
     /* pConfigOption */
     NULL_PTR,
     
     /* pClientTimer */
     &Sd_GSaaClientTimerStatic[2],
     
     /* usHandleId */
     0x1,
     
     /* usEventGroupId */
     0x5,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddBaseMulticastSoConGrp */
     0x0,
     
     /* ddNoOfMulticastSoConGrp */
     0x0,
     
     /* usClientServiceIndex */
     0x0,
     
     /* usConEvGrpSelfIndex */
     0x1,
     
     /* ucCounter */
     0x0,
     
     /* stConsumedEvGrpStaticFlag */
     {
       
       /* blAutoRequire */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       0,
       
       /* ucReserved */
       0
     }
   },
   /* Sd_GaaConsumedEvGrpStatic : 
       	2 - SdInstance_0_CSI_EnhancedTestabilityServiceLow_CSI_EnhancedTestabilityServiceLow_EventGroupId_6 */
   {
     
     /* pConfigOption */
     NULL_PTR,
     
     /* pClientTimer */
     &Sd_GSaaClientTimerStatic[3],
     
     /* usHandleId */
     0x2,
     
     /* usEventGroupId */
     0x6,
     
     /* usOtherservKeyIndex */
     0x0,
     
     /* usOtherservKeyLength */
     0x0,
     
     /* ddMulticastActivationRoGrpId */
     0x0,
     
     /* ddTcpActivationRoGrpId */
     0x0,
     
     /* ddUdpActivationRoGrpId */
     0x0,
     
     /* ddBaseMulticastSoConGrp */
     0x0,
     
     /* ddNoOfMulticastSoConGrp */
     0x0,
     
     /* usClientServiceIndex */
     0x0,
     
     /* usConEvGrpSelfIndex */
     0x2,
     
     /* ucCounter */
     0x0,
     
     /* stConsumedEvGrpStaticFlag */
     {
       
       /* blAutoRequire */
       0,
       
       /* blMulticastActivationRoGrpIdPresent */
       0,
       
       /* blTcpActivationRoGrpIdPresent */
       0,
       
       /* blUdpActivationRoGrpIdPresent */
       0,
       
       /* ucReserved */
       0
     }
   }
    };
      #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
      #include "Sd_MemMap.h" 

       
    #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
     #include "Sd_MemMap.h"
     const Sd_SoConGroupStaticType Sd_GaaSoConGroupStatic[4] =
     {
   /*  Sd_GaaSoConGroupStatic : 0 - SoAdConfig_0_SoAdSocketConnectionGroup_Client_EnhancedTestabilityServiceLow  */
   {
     
     /* usBaseSocketConIndex */
     0,
     
     /* usNoOfSockets */
      0x4 
   },
   /*  Sd_GaaSoConGroupStatic : 1 - SoAdConfig_0_SoAdSocketConnectionGroup_EngineManagementSystem_TCP  */
   {
     
     /* usBaseSocketConIndex */
     4,
     
     /* usNoOfSockets */
      0x1 
   },
   /*  Sd_GaaSoConGroupStatic : 2 - SoAdConfig_0_SoAdSocketConnectionGroup_EngineManagementSystem_UDP  */
   {
     
     /* usBaseSocketConIndex */
     5,
     
     /* usNoOfSockets */
      0x4 
   },
   /*  Sd_GaaSoConGroupStatic : 3 - SoAdConfig_0_SoAdSocketConnectionGroup_Server_EnhancedTestabilityServiceLow  */
   {
     
     /* usBaseSocketConIndex */
     9,
     
     /* usNoOfSockets */
      0x3 
   }
    };
        #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
        #include "Sd_MemMap.h" 

       
   #define SD_START_SEC_CONFIG_DATA_UNSPECIFIED
   #include "Sd_MemMap.h"
   const Sd_InstanceStaticType Sd_GaaInstanceStatic[1] =
   {
     /* Sd_GaaInstanceStatic : 0 - SdInstance_0 */
     {
       
       /* pConfigOption */
       NULL_PTR,
       
       /* usBaseServerServiceIndex */
       0x0,
       
       /* usNoOfServerServices */
       0x2,
       
       /* usBaseClientServiceIndex  */
       0x0,
       
       /* usNoOfClientServices */
       0x1,
       
       /* ddTxPduId */
       0x3,
       
       /* ddUnicastRxPduId */
       0x1,
       
       /* ddMulticastRxPduId */
       0x0,
       
       /* ddIpAddrSoConId */
       0x5,
       
       /* ddRxUnicastSoConId */
       0xD,
       
       /* ddRxMulticastSoConId */
       0x4,
       
       /* usDemErrorMalformedId */
       0x1D,
       
       /* usDemErrorOutOfResId */
       0x1E,
       
       /* usDemErrorSubEventgroupNacId */
       0x1F,
       
       /* ucInstanceSelfIndex */
       0x0,
       
       /* blDomainIpv4 */
       (boolean)SD_TRUE,
       
       /* usSdInstanceLocalAdressCheckLength */
       SD_INVALID
     }
   };
       
      #define SD_STOP_SEC_CONFIG_DATA_UNSPECIFIED
      #include "Sd_MemMap.h" 
   
  
 #define SD_START_SEC_CONST_UNSPECIFIED
 #include "Sd_MemMap.h"
  const Sd_ProviderConsumerListType Sd_GaaClientServiceAllowedProviderStatic[1] =
 {
/* Sd_GaaClientServiceAllowedProviderStatic  */
{
  
  /* usServiceId */
  259,
  
  /* ListMemberType */
  SD_CONSUMER_TYPE,
  
  /* SdIpAddressType */
  SD_AF_INET,
  
  /* AllowedProviderAddress */
  {192,168,1,2}
}
 };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h" 
  #define SD_START_SEC_CONST_UNSPECIFIED
  #include "Sd_MemMap.h"
   const Sd_ProviderConsumerListType Sd_GaaServerServiceAllowedConsumerStatic[1U] =
  {
 /* Sd_GaaServerServiceAllowedConsumerStatic  */
 {
   
   /* usServiceId */
   260,
   
   /* ListMemberType */
   SD_CONSUMER_TYPE,
   
   /* SdIpAddressType */
   SD_AF_INET,
   
   /* AllowedProviderAddress */
   {192,168,1,2}
 }
  };
    #define SD_STOP_SEC_CONST_UNSPECIFIED
    #include "Sd_MemMap.h" 
      
     
  
 
 
 
 
 
 
 
    

   #define SD_START_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h"
   const Sd_NvMRomBlockData_type Sd_Gaa_NvMRomBlockData[1] =
   {
       {
       	
   1,
   0,
   
               {
   {
     
     /* usServiceId */
     260,
     
     /* ListMemberType */
     SD_CONSUMER_TYPE,
     
     /* SdIpAddressType */
     SD_AF_INET,
     
     /* AllowedProviderAddress */
     {192,168,1,2}
   },
   {
     
     /* usServiceId */
     259,
     
     /* ListMemberType */
     SD_PROVIDER_TYPE,
     
     /* SdIpAddressType */
     SD_AF_INET,
     
     /* AllowedProviderAddress */
     {192,168,1,2}
   }
           }
       
       
   
       }
   };
   #define SD_STOP_SEC_CONST_UNSPECIFIED
   #include "Sd_MemMap.h" 
        #define SD_START_SEC_VAR_INIT_UNSPECIFIED
        #include "Sd_MemMap.h"
           Sd_NvMRamBlockData_type Sd_Gaa_NvMRamBlockData[1] =
        {
          { 
   
        1,
        0  ,
         	 
        
        {
        {
          
          /* usServiceId */
          260,
          
          /* ListMemberType */
          SD_CONSUMER_TYPE,
          
          /* SdIpAddressType */
          SD_AF_INET,
          
          /* AllowedProviderAddress */
          {0,0,192,168,1,2}
        },
        {
          
          /* usServiceId */
          259,
          
          /* ListMemberType */
          SD_PROVIDER_TYPE,
          
          /* SdIpAddressType */
          SD_AF_INET,
          
          /* AllowedProviderAddress */
          {0,0,192,168,1,2}
        }
        ,{
          
          /* usServiceId */
          260,
          
          /* ListMemberType */
          SD_CONSUMER_TYPE,
          
          /* SdIpAddressType */
          SD_WILDCARD_DOMAIN,
          
          /* AllowedProviderAddress */
          {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
        }
         ,{
           
           /* usServiceId */
           259,
           
           /* ListMemberType */
           SD_PROVIDER_TYPE,
           
           /* SdIpAddressType */
           SD_WILDCARD_DOMAIN,
           
           /* AllowedProviderAddress */
           {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
         }
         
         
     
          
                   }
                   
         
           
            
                  
              }
           };
           #define SD_STOP_SEC_VAR_INIT_UNSPECIFIED
           #include "Sd_MemMap.h" 
     
   
           

/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
